name: Action flows

on: [push]
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repos
        uses: actions/checkout@v3
      
      - name: List Files
        run: |
          pwd
          ls

      - name: simple js action
        uses: actions/hello-world-javascript-action@v1 # even we can reference specific commit
        id: greet
        with:
          who-to-greet: Harry

      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"