name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
        continue-on-error: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Log node version
        run: node -v